name: CI/CD Deploy to k3s

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image
      run: |
        docker build -t apervachev/website-1:latest .
        docker push apervachev/website-1:latest

    - name: Deploy to Oracle VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.ORACLE_HOST }}
        username: ubuntu
        key: ${{ secrets.ORACLE_SSH_KEY }}
        script: |
          export KUBECONFIG=$HOME/.kube/config
          cd ~/k8s/website-1
          kubectl rollout restart deployment website-1
